### PR TITLE
Add advice for Thread.sleep() replacement with Thread.onSpinWait()

### PR DESCRIPTION
**Pull request by stsypanov**
According to [JavaDoc](https://docs.oracle.com/javase/9/docs/api/java/lang/Thread.html#onSpinWait--)  `Thread.onSpinWait()` is preferable in spin-wait loop constructions.

### CODE REVIEW

**Comment by leventov** [comment]
I have doubts the example code from `Thread.onSpinWait()` is sound. I've opened [a thread in concurrency-interest about this](http://cs.oswego.edu/pipermail/concurrency-interest/2019-November/016978.html), let's see what the experts say.

**Comment by stsypanov** [comment]
@leventov hello, I've added this as a general recommendation for developers to pay attention to this pattern. According to https://ionutbalosin.com/2018/06/onspinwait-method-from-thread-class/ there are other possible substitutions like `Thread.yield()` or `Object.wait()`/`Object.notify()`. In https://youtrack.jetbrains.com/issue/IDEA-226838 Tagir Valeev suggests just to turn corresponding inspection on by default without any quick fix.

So let's wait for the replies, maybe then I'll drop replacement suggestion and leave only pay-attention notation.

**Comment by leventov** [comment]
I agree with Tagir's suggestion about synchronization primitive. So would rather add a checklist item mirroring IntelliJ's busy wait inspection, that is, about replacing busy wait with normal synchronization.

The standard way of framing the item w.r.t. the exceptional cases in this checklist is like: "if there is a busy wait loop, **is it explained in a comment** why it's needed in the specific case, and that the costs and potential problems associated with busy waiting either don't apply in the specific case, or are outweighed by the benefits?"

**Comment by stsypanov** [comment]
I've redesigned my changes. Please review. Also I've got one more tiny suggestion about replacement of 
```java
Thread.sleep(TimeUnit.SECONDS.toMillis(1L));
```
with
```java
TimeUnit.SECONDS.sleep(1L);
```
Do you think this one is worth adding and if it does, then what is the appropriate part?

**Comment by leventov** [comment]
I've adjusted and merged via #9. Thanks for the contribution!

**Comment by stsypanov** [comment]
Cool! @leventov what about replacement of 
```java
Thread.sleep(TimeUnit.SECONDS.toMillis(1L));
```
with
```java
TimeUnit.SECONDS.sleep(1L);
```
Do you think this one is worth adding and if it does, then what is the appropriate part?

**Comment by leventov** [comment]
I've included `TimeUnit.SECONDS.sleep()` already in the adjustments

**Comment by stsypanov** [comment]
Yes, the patch includes it in code snippet:
```java
while (!condition) {
  // Or Thread.sleep/yield/onSpinWait, or no statement, i. e. a pure spin wait
  TimeUnit.SECONDS.sleep(1L);
}
```
I mean, maybe it should be included as a separate advice?

**Comment by leventov** [comment]
I see. I think it could be mentioned in [Tm.3](https://github.com/code-review-checklists/java-concurrency#time-units) in an extra sentence.

**Pull request closed without merging**
